### ISSUE TITLE
VABS

### ISSUE THREAD

**Issue by EVElove444** [ptrbortolotti/SONATA#10]
download the solvers VABS (commercial, use wine to run it on mac/linux systems)。VABS I applied to them and never got a reply, do you have a better way?

**Comment by ptrbortolotti** [comment]
I'm not sure I understand the question... however I'll say that we are stopping the support of the commercial solver VABS, and moving forward we will rely on the open-source alternative ANBA4. In other words, you don't need VABS to run SONATA
