### ISSUE TITLE
installation failed after many tries

### ISSUE THREAD

**Issue by pcasalone** [ptrbortolotti/SONATA#2]
Hello everybody,
I am Pietro Casalone, a PhD student from Politecnico di Torino. I want to use Sonata in my phd thesis on fluid structure interaction and optimization of hydrofoil in composite materials.
Unfortunately I am not able to succesfully install Sonata. When i run the examples i get an error thrown by OCC. indeed for me was not possible to download OCC 7.4.1. (only newer version.)
The installation procedure that is suggested on git also encounters some conflicts between packages. 
I have also tried the installation procedure on the other repo (https://gitlab.lrz.de/HTMWTUM/SONATA) unsuccesfully
 
I am trying make it work on a Ubuntu 20.04.05 LTS (focal fossa) (tried also the newer version 22.04) following the procedure on git thoroughly and i have tried many times but I am not succeeding.

Can you please suggest another OS or installation procedure that is working for you??

Many thanks 

Pietro

**Comment by ptrbortolotti** [comment]
Hello Pietro,
this is frustrating, I'm sorry for not being able to compile SONATA. The conflicts between libraries on condo are common and are not easy to resolve. We can try debugging this on our side, please let us know if you succeed in the meanwhile. 
I believe that SONATA is no longer maintained at TUM and I am not surprised to hear that https://gitlab.lrz.de/HTMWTUM/SONATA does not work either.
Talk soon,
Pietro

**Comment by pietrocasa** [comment]
Hello Pietro, 
unfortunately I did not manage to successfully install Sonata.
Can you please tell me what version of linux and packages are you using to make it work?

I have another short question: does ANBA4/sonata account for initial twist and curvature of the blade (like VABS) or that part has not been implemented yet? 

Many thanks,

Pietro

**Comment by ptrbortolotti** [comment]
Hello Pietro,
I've done some work to update the code, resolve conflicts, clean up outdated lines, and update the installation instructions. Could you please try the installation again?
Thank you and best regards,
Pietro

**Comment by ptrbortolotti** [comment]
I will close this for now, please reopen it if the issue persists
